# Generated by Django 3.0.9 on 2020-08-07 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Bedroom', 'Bedroom'), ('Bathroom', 'Bathroom'), ('Kitchen', 'Kitchen'), ('Living Room', 'Living Room'), ('Dining Room', 'Dining Room'), ('Closet', 'Closet'), ('HVAC', 'HVAC'), ('IR', 'Infrared'), ('Smoke', 'Smoke, Gas and Alcohol')], max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('sensor', models.CharField(choices=[('LIDAR', 'LIDAR'), ('Pressure', 'Pressure'), ('Temperature', 'Temperature'), ('Proximity', 'Proximity'), ('Ultrasonic', 'Ultrasonic'), ('Flow', 'Flow and Level'), ('Humidity', 'Humidity'), ('IR', 'Infrared'), ('Smoke', 'Smoke, Gas and Alcohol')], max_length=15)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor_ID', models.CharField(max_length=20)),
                ('is_entertainment', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Room')),
            ],
        ),
    ]
