# Generated by Django 3.0.9 on 2020-08-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_on',
            field=models.BooleanField(default=False),
        ),
    ]
