# Generated by Django 3.0.9 on 2020-08-09 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20200809_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAutomations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_avail', models.BooleanField(default=False)),
                ('time', models.CharField(choices=[('after_sunrise', 'Day (After sunrise)'), ('after_sunset', 'Night (After sunset)')], max_length=20)),
                ('activity', models.CharField(choices=[('room_in', 'Entering the room'), ('room_out', 'Exiting the room'), ('room_in_entertainment', 'Room in entertainment'), ('room_in_non_entertainment', 'Room in non-entertainment')], max_length=30)),
                ('weather', models.CharField(choices=[('cloudy', 'Cloudy'), ('not_cloudy', 'Not Cloudy')], max_length=30)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
    ]
