# Generated by Django 3.0.9 on 2020-08-09 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_availableautomations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvailableAutomations',
            new_name='AvailableAutomation',
        ),
    ]
