# Generated by Django 3.0.9 on 2020-08-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20200809_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableautomation',
            name='automation',
            field=models.CharField(choices=[('On', 'On'), ('Off', 'Off')], default='Off', max_length=5),
        ),
    ]
