# Generated by Django 3.0.9 on 2020-08-10 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_availableautomation_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableautomation',
            name='activity',
            field=models.CharField(choices=[('room_in', 'Entering the room'), ('room_out', 'Exiting the room'), ('room_in_entertainment', 'Room in entertainment'), ('room_in_non_entertainment', 'Room in non-entertainment'), ('room_in_sleeping', 'Sleeping')], max_length=30),
        ),
    ]
