# Generated by Django 3.0.9 on 2020-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_hvac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hvac',
            name='power',
            field=models.CharField(choices=[('Power Saver', 'Power Saver'), ('Normal', 'Normal')], default='Power Saver', max_length=20),
        ),
        migrations.AlterField(
            model_name='hvac',
            name='temp',
            field=models.IntegerField(default=72),
        ),
    ]
