# Generated by Django 3.0.9 on 2020-08-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_auto_20200810_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='sensor_ID',
            field=models.CharField(max_length=30),
        ),
    ]
