# Generated by Django 3.1 on 2020-09-01 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_auto_20200810_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='sensor',
        ),
    ]
